[workspace]

members = [
    "packages/aoc",
    "packages/day_01",
    "packages/day_02",
    "packages/day_03",
    "packages/day_04",
    "packages/day_05",
    "packages/day_06",
    "packages/day_07",
    "packages/day_08",
]
